package masterdata

import (
	"time"

	"github.com/Fernlizer/Breed-inquiry-Golang-Fiber-Backend/internal/domain"
)

// BreedMasterData ข้อมูลตั้งต้นของพันธุ์วัว (รวมครบตามโจทย์ SQL)
var BreedMasterData = []domain.Breed{
	{
		ID:          "10011001",
		NameEn:      "ABERDEEN ANGUS",
		NameTh:      "อาเบอร์ดีน แองกัส",
		ShortName:   "AN",
		Remark:      "",
		CreatedAt:   time.Now(),
		CreatedByID: "SYSTEM",
		CreatedBy:   "SYSTEM",
		UpdatedAt:   time.Now(),
		UpdatedByID: "SYSTEM",
		UpdatedBy:   "SYSTEM",
	},
	{
		ID:          "10011007",
		NameEn:      "AMERICAN BRAHMAN",
		NameTh:      "อเมริกัน บราห์มัน",
		ShortName:   "ABM",
		Remark:      "",
		CreatedAt:   time.Now(),
		CreatedByID: "SYSTEM",
		CreatedBy:   "SYSTEM",
		UpdatedAt:   time.Now(),
		UpdatedByID: "SYSTEM",
		UpdatedBy:   "SYSTEM",
	},
	{
		ID:          "10011040",
		NameEn:      "BEEFMASTER",
		NameTh:      "บีฟมาสเตอร์",
		ShortName:   "BM",
		Remark:      "",
		CreatedAt:   time.Now(),
		CreatedByID: "SYSTEM",
		CreatedBy:   "SYSTEM",
		UpdatedAt:   time.Now(),
		UpdatedByID: "SYSTEM",
		UpdatedBy:   "SYSTEM",
	},
	{
		ID:          "10011053",
		NameEn:      "BLACK ANGUS",
		NameTh:      "แบล็คแองกัส",
		ShortName:   "BAN",
		Remark:      "",
		CreatedAt:   time.Now(),
		CreatedByID: "SYSTEM",
		CreatedBy:   "SYSTEM",
		UpdatedAt:   time.Now(),
		UpdatedByID: "SYSTEM",
		UpdatedBy:   "SYSTEM",
	},
	{
		ID:          "10011066",
		NameEn:      "BRAHMAN",
		NameTh:      "บราห์มัน",
		ShortName:   "BR",
		Remark:      "",
		CreatedAt:   time.Now(),
		CreatedByID: "SYSTEM",
		CreatedBy:   "SYSTEM",
		UpdatedAt:   time.Now(),
		UpdatedByID: "SYSTEM",
		UpdatedBy:   "SYSTEM",
	},
	{
		ID:          "10011070",
		NameEn:      "BRANGUS",
		NameTh:      "แบรงกัส",
		ShortName:   "BN",
		Remark:      "",
		CreatedAt:   time.Now(),
		CreatedByID: "SYSTEM",
		CreatedBy:   "SYSTEM",
		UpdatedAt:   time.Now(),
		UpdatedByID: "SYSTEM",
		UpdatedBy:   "SYSTEM",
	},
	{
		ID:          "10011086",
		NameEn:      "CHARBRAY X ZEBU",
		NameTh:      "ชาร์เบรย์ x ซีบู",
		ShortName:   "CB",
		Remark:      "",
		CreatedAt:   time.Now(),
		CreatedByID: "SYSTEM",
		CreatedBy:   "SYSTEM",
		UpdatedAt:   time.Now(),
		UpdatedByID: "SYSTEM",
		UpdatedBy:   "SYSTEM",
	},
	{
		ID:          "10011088",
		NameEn:      "CHAROLAIS",
		NameTh:      "ชาร์โรเลส์",
		ShortName:   "CH",
		Remark:      "",
		CreatedAt:   time.Now(),
		CreatedByID: "SYSTEM",
		CreatedBy:   "SYSTEM",
		UpdatedAt:   time.Now(),
		UpdatedByID: "SYSTEM",
		UpdatedBy:   "SYSTEM",
	},
	{
		ID:          "10011115",
		NameEn:      "DROUGHTMASTER",
		NameTh:      "เดร้าท์มาสเตอร์",
		ShortName:   "DZ",
		Remark:      "",
		CreatedAt:   time.Now(),
		CreatedByID: "SYSTEM",
		CreatedBy:   "SYSTEM",
		UpdatedAt:   time.Now(),
		UpdatedByID: "SYSTEM",
		UpdatedBy:   "SYSTEM",
	},
	{
		ID:          "10011162",
		NameEn:      "INDO BRAZILIAN",
		NameTh:      "ฮินดูบราซิล",
		ShortName:   "IB",
		Remark:      "",
		CreatedAt:   time.Now(),
		CreatedByID: "SYSTEM",
		CreatedBy:   "SYSTEM",
		UpdatedAt:   time.Now(),
		UpdatedByID: "SYSTEM",
		UpdatedBy:   "SYSTEM",
	},
	{
		ID:          "10011171",
		NameEn:      "KABIN BURI",
		NameTh:      "กบินทร์บุรี",
		ShortName:   "KB",
		Remark:      "",
		CreatedAt:   time.Now(),
		CreatedByID: "SYSTEM",
		CreatedBy:   "SYSTEM",
		UpdatedAt:   time.Now(),
		UpdatedByID: "SYSTEM",
		UpdatedBy:   "SYSTEM",
	},
	{
		ID:          "10011187",
		NameEn:      "LIMOUSIN",
		NameTh:      "ลิมูซิน",
		ShortName:   "LM",
		Remark:      "",
		CreatedAt:   time.Now(),
		CreatedByID: "SYSTEM",
		CreatedBy:   "SYSTEM",
		UpdatedAt:   time.Now(),
		UpdatedByID: "SYSTEM",
		UpdatedBy:   "SYSTEM",
	},
	{
		ID:          "10011247",
		NameEn:      "RED ANGUS",
		NameTh:      "แองกัสแดง",
		ShortName:   "AR",
		Remark:      "",
		CreatedAt:   time.Now(),
		CreatedByID: "SYSTEM",
		CreatedBy:   "SYSTEM",
		UpdatedAt:   time.Now(),
		UpdatedByID: "SYSTEM",
		UpdatedBy:   "SYSTEM",
	},
	{
		ID:          "10011248",
		NameEn:      "RED BRAHMAN",
		NameTh:      "บราห์มันแดง",
		ShortName:   "RR",
		Remark:      "",
		CreatedAt:   time.Now(),
		CreatedByID: "SYSTEM",
		CreatedBy:   "SYSTEM",
		UpdatedAt:   time.Now(),
		UpdatedByID: "SYSTEM",
		UpdatedBy:   "SYSTEM",
	},
	{
		ID:          "10011249",
		NameEn:      "RED BRANGUS",
		NameTh:      "แบรงกัสแดง",
		ShortName:   "RBR",
		Remark:      "",
		CreatedAt:   time.Now(),
		CreatedByID: "SYSTEM",
		CreatedBy:   "SYSTEM",
		UpdatedAt:   time.Now(),
		UpdatedByID: "SYSTEM",
		UpdatedBy:   "SYSTEM",
	},
	{
		ID:          "10011278",
		NameEn:      "SHORTHORN",
		NameTh:      "ชอตฮอร์น",
		ShortName:   "SS",
		Remark:      "",
		CreatedAt:   time.Now(),
		CreatedByID: "SYSTEM",
		CreatedBy:   "SYSTEM",
		UpdatedAt:   time.Now(),
		UpdatedByID: "SYSTEM",
		UpdatedBy:   "SYSTEM",
	},
	{
		ID:          "10011281",
		NameEn:      "SIMMENTAL",
		NameTh:      "ซิมเมนทอล",
		ShortName:   "SM",
		Remark:      "",
		CreatedAt:   time.Now(),
		CreatedByID: "SYSTEM",
		CreatedBy:   "SYSTEM",
		UpdatedAt:   time.Now(),
		UpdatedByID: "SYSTEM",
		UpdatedBy:   "SYSTEM",
	},
	{
		ID:          "10011291",
		NameEn:      "TAK",
		NameTh:      "ตาก",
		ShortName:   "TK",
		Remark:      "",
		CreatedAt:   time.Now(),
		CreatedByID: "SYSTEM",
		CreatedBy:   "SYSTEM",
		UpdatedAt:   time.Now(),
		UpdatedByID: "SYSTEM",
		UpdatedBy:   "SYSTEM",
	},
	{
		ID:          "10011297",
		NameEn:      "THAI BRAHMAN",
		NameTh:      "ไทยบราห์มัน",
		ShortName:   "TBR",
		Remark:      "",
		CreatedAt:   time.Now(),
		CreatedByID: "SYSTEM",
		CreatedBy:   "SYSTEM",
		UpdatedAt:   time.Now(),
		UpdatedByID: "SYSTEM",
		UpdatedBy:   "SYSTEM",
	},
	{
		ID:          "10011315",
		NameEn:      "ZEBU (UNSPECIFIED)",
		NameTh:      "ซีบู",
		ShortName:   "ZE",
		Remark:      "",
		CreatedAt:   time.Now(),
		CreatedByID: "SYSTEM",
		CreatedBy:   "SYSTEM",
		UpdatedAt:   time.Now(),
		UpdatedByID: "SYSTEM",
		UpdatedBy:   "SYSTEM",
	},
	{
		ID:          "10012002",
		NameEn:      "BROWN SWISS",
		NameTh:      "บราวน์สวิส",
		ShortName:   "BS",
		Remark:      "",
		CreatedAt:   time.Now(),
		CreatedByID: "SYSTEM",
		CreatedBy:   "SYSTEM",
		UpdatedAt:   time.Now(),
		UpdatedByID: "SYSTEM",
		UpdatedBy:   "SYSTEM",
	},
	{
		ID:          "10012004",
		NameEn:      "HEREFORD",
		NameTh:      "เฮียร์ฟอร์ด",
		ShortName:   "HB",
		Remark:      "",
		CreatedAt:   time.Now(),
		CreatedByID: "SYSTEM",
		CreatedBy:   "SYSTEM",
		UpdatedAt:   time.Now(),
		UpdatedByID: "SYSTEM",
		UpdatedBy:   "SYSTEM",
	},
	{
		ID:          "10012005",
		NameEn:      "HOLSTEIN FRIESIAN",
		NameTh:      "โฮลสไตน์ ฟรีเชี่ยน",
		ShortName:   "HO",
		Remark:      "",
		CreatedAt:   time.Now(),
		CreatedByID: "SYSTEM",
		CreatedBy:   "SYSTEM",
		UpdatedAt:   time.Now(),
		UpdatedByID: "SYSTEM",
		UpdatedBy:   "SYSTEM",
	},
	{
		ID:          "10012006",
		NameEn:      "JERSEY",
		NameTh:      "เจอร์ซี",
		ShortName:   "JE",
		Remark:      "",
		CreatedAt:   time.Now(),
		CreatedByID: "SYSTEM",
		CreatedBy:   "SYSTEM",
		UpdatedAt:   time.Now(),
		UpdatedByID: "SYSTEM",
		UpdatedBy:   "SYSTEM",
	},
	{
		ID:          "10012011",
		NameEn:      "THAI FRIESIAN",
		NameTh:      "ไทยฟรีเซียน",
		ShortName:   "TF",
		Remark:      "",
		CreatedAt:   time.Now(),
		CreatedByID: "SYSTEM",
		CreatedBy:   "SYSTEM",
		UpdatedAt:   time.Now(),
		UpdatedByID: "SYSTEM",
		UpdatedBy:   "SYSTEM",
	},
	{
		ID:          "10012012",
		NameEn:      "THAI MILKING ZEBU",
		NameTh:      "ทีเอ็มแซด",
		ShortName:   "TMZ",
		Remark:      "",
		CreatedAt:   time.Now(),
		CreatedByID: "SYSTEM",
		CreatedBy:   "SYSTEM",
		UpdatedAt:   time.Now(),
		UpdatedByID: "SYSTEM",
		UpdatedBy:   "SYSTEM",
	},
	{
		ID:          "10012013",
		NameEn:      "TROPICAL HOLSTEIN",
		NameTh:      "ทรอปิคอลโฮลสไตน์",
		ShortName:   "TH",
		Remark:      "",
		CreatedAt:   time.Now(),
		CreatedByID: "SYSTEM",
		CreatedBy:   "SYSTEM",
		UpdatedAt:   time.Now(),
		UpdatedByID: "SYSTEM",
		UpdatedBy:   "SYSTEM",
	},
	{
		ID:          "10013001",
		NameEn:      "THAI NATIVE",
		NameTh:      "พันธุ์พื้นเมือง",
		ShortName:   "THN",
		Remark:      "",
		CreatedAt:   time.Now(),
		CreatedByID: "SYSTEM",
		CreatedBy:   "SYSTEM",
		UpdatedAt:   time.Now(),
		UpdatedByID: "SYSTEM",
		UpdatedBy:   "SYSTEM",
	},
	{
		ID:          "10010998",
		NameEn:      "CROSSBRED",
		NameTh:      "ลูกผสม",
		ShortName:   "MX",
		Remark:      "",
		CreatedAt:   time.Now(),
		CreatedByID: "SYSTEM",
		CreatedBy:   "SYSTEM",
		UpdatedAt:   time.Now(),
		UpdatedByID: "SYSTEM",
		UpdatedBy:   "SYSTEM",
	},
	{
		ID:          "10010999",
		NameEn:      "OTHER CATTLE",
		NameTh:      "โคสายพันธุ์อื่นๆ",
		ShortName:   "ETC",
		Remark:      "",
		CreatedAt:   time.Now(),
		CreatedByID: "SYSTEM",
		CreatedBy:   "SYSTEM",
		UpdatedAt:   time.Now(),
		UpdatedByID: "SYSTEM",
		UpdatedBy:   "SYSTEM",
	},
}
