app:
  name: "Breed Inquiry API"
  env: "development"
  port: 4000
  enable_prefork: false
  disable_startup_message: false
  enable_print_routes: false

database:
  driver: "postgres"
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "fern"
  name: "greenmoons"
  sslmode: "disable"

backup:
  enable: true
  retention_days: 120
  pg_dump_path: "C:\\Program Files\\PostgreSQL\\17\\bin\\pg_dump.exe"
