app:
  name: "Breed Inquiry API"
  env: "development" # development, production
  port: 4000
database:
  driver: "postgres" # postgres, mysql
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "fern"
  name: "greenmoons"
  sslmode: "disable"
backup:
  enable: true
  retention_days: 120 # กำหนดให้เก็บไฟล์ backup ไว้ 120 วัน
  pgDumpPath: 'C:\Program Files\PostgreSQL\17\bin\pg_dump.exe' # ว่างไว้ใช้ค่าเริ่มต้นของ OS
