app:
  name: "Breed Inquiry API"
  env: "development" # development, production
  port: 4000
database:
  driver: "postgres" # postgres, mysql
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "fern"
  name: "greenmoons"
  sslmode: "disable"
